name: David Macek
favicon: null
layout_spectrum: 0.36282
typography_spectrum: 0.47971
title: "Let's Collaborate for a Better World"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4c4040'
    - '#040404'
    - '#eebf9d'
    - '#80655a'
    - '#9e9e9e'
  brandStrength: 0.625
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
